### DISCUSSION TITLE
Cannot start container / cannot get it working

### DISCUSSION THREAD

**Discussion by clemone210** [qdm12/ddns-updater#142] [Q&A]
Hello,
I am trying to setup this container with docker-compose.

I set up my directory /home/user/ddns
as well as the data folder /home/user/ddns/data

The docker-compose.yml file looks like this:

```yml
version: "3.7"
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    volumes:
      - ./data:/updater/data
    environment:
      - CONFIG=/home/timo/ddns/data/config.json
      - PERIOD=5m
      - IP_METHOD=cycle
      - IPV4_METHOD=cycle
      - IPV6_METHOD=cycle
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_ENCODING=console
      - LOG_LEVEL=info
      - GOTIFY_URL=
      - GOTIFY_TOKEN=
    restart: always

```

My config looks like this:

 ```json
{
     "settings": [
         {
             "provider": "strato.de",
             "domain": "my.domain",
             "host": "cloud,test",
             "password": "Mypassword"
         }
     ]
 }
```

Can someone tell me what am I doing wrong?

If I run docker-compose up -d in the directory it starts the container but with `docker ps` I see that the container restarts every 5 seconds or so.

The log says: 

```
2021-01-11T16:50:27.936048543Z Running version latest built on 2020-12-30T19:51:20Z (commit d8a7fef)
2021-01-11T16:50:27.936059364Z
2021-01-11T16:50:27.936067206Z
2021-01-11T16:50:27.936074796Z 🔧  Need help? https://github.com/qdm12/ddns-updater/issues/new
2021-01-11T16:50:27.936082878Z 💻  Email? quentin.mcgaw@gmail.com
2021-01-11T16:50:27.936090807Z ☕  Slack? Join from the Slack button on Github
2021-01-11T16:50:27.936098796Z 💸  Help me? https://github.com/sponsors/qdm12
2021-01-11T16:50:27.941114341Z 2021-01-11T16:50:27.940Z ERROR   unexpected end of JSON input

```

**Comment by qdm12** [comment]
You need to remove `CONFIG=/home/timo/ddns/data/config.json`. This is to have your entire JSON file content on a single line. I'll remove it from the default docker-compose.yml as it is indeed confusing.

You can also use `docker-compose up` to run the container interactively and stop it with CTRL+C

**Reply by clemone210** [reply]
So I need to enter the whole config in the „CONFIG=„ line?

**Reply by clemone210** [reply]
> So I need to enter the whole config in the „CONFIG=„ line?

So I entered everything into one line, but still the same error. What am I doing wrong?

**Reply by qdm12** [reply]
No just remove it or leave it blank haha

**Reply by clemone210** [reply]
> No just remove it or leave it blank haha

If I delete the line "CONFIG=" I still get the error:

`ddns-updater    | 2021-01-12T12:53:26.623Z      ERROR   unexpected end of JSON input`

If I leave the line and do not enter anything, I get the same error as well. I dont know what I am doing wrong :D

**Reply by qdm12** [reply]
Maybe you have windows line endings 🤔 Let me know if that's the case I'll add some sanitization code as well. Other than that I'm not sure the JSON you posted looks fine to me.

Otherwise you can try putting your config in the CONFIG environment variable but it has to hold on a single line (so remove all new lines).

**Reply by clemone210** [reply]
> Maybe you have windows line endings 🤔 Let me know if that's the case I'll add some sanitization code as well. Other than that I'm not sure the JSON you posted looks fine to me.
> 
> Otherwise you can try putting your config in the CONFIG environment variable but it has to hold on a single line (so remove all new lines).

I now created the `docker-compose.yml` within `nano` without pasting anything.
Either with nor without the config line it still says `ddns-updater    | 2021-01-12T16:18:16.151Z      ERROR   unexpected end of JSON input`

I am loosing my mind :D
May can you show me how the single line config for strato.de looks like?

**Reply by clemone210** [reply]
This is how it looks now:

```yml
version: "3.7"
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    volumes:
      - ./data:/updater/data
    environment:
      {"settings":[{"provider":"strato.de","domain":"my.domain","host":"cloud,test","password":"Mypassword"}]}

      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_ENCODING=console
      - LOG_LEVEL=info
      - GOTIFY_URL=
      - GOTIFY_TOKEN=
    restart: always
```

Can you maybe format it like it should be? would that be possible? 
Id like to give you a dono afterwards if you can solve my problem 👍
