### DISCUSSION TITLE
permission denied to /updater/data/updates.json

### DISCUSSION THREAD

**Discussion by Taseen18** [qdm12/ddns-updater#413] [Q&A] [answered]
I get this error message in the logs when I attempt to startup. I have posted an issue on the issues tab. Anyone else experienced this?

2023-01-09T17:02:31Z ERROR open /updater/data/updates.json: permission denied
2023-01-09T17:02:31Z INFO Shutdown successful

**Comment by tgaertner** [comment]
Had the same error.

Go to your docker settings and change 

Config: from "/mnt/user/appdata/ddns-updater" to "/mnt/user/appdata/ddns-updater/data" 

At least it solved it for me.

**Comment by haferm** [comment]
had the same, follow the exact setup procedure.. https://github.com/qdm12/ddns-updater#setup

**Comment by daendaen** [comment]
I would like to use the ddns updater under unraid

I created the config.json file. but still get the error message


![2](https://user-images.githubusercontent.com/44930653/217022424-897fd6ad-38f0-42c0-ac52-a7d822d0daac.png)
![1](https://user-images.githubusercontent.com/44930653/217022430-ee01fec1-d046-4442-a091-297bbb9e55a2.png)

**Reply by tgaertner** [reply]
What is the value for your "Config" setting like? (I didn't touched the advanced settings)

**Reply by daendaen** [reply]
the problem was because of the authorization of the folder. it was set to nobody 99. this seems to be the default for unraid. I then changed s to 1000, now everything works

![3](https://user-images.githubusercontent.com/44930653/217030684-f8d69b17-cf9b-4fa2-bb67-5f8d6f66e0f2.png)

**Comment by andymaycoates** [comment]
I had a similar issue on my Synology NAS where the container log informed me that updates.json could not be created due to a permissions issue. I found that the container was trying to write the updates.json file with the UID:GID of 1000:1000, which did not exist on my NAS. You can see these args in the Dockerfile, and they cannot be replaced by ENV variables.

To fix this issue, I noted the UID:GID of another suitable NAS user (ensuring that said user had write permissions on the share mapped to /updater/data in the container) and then instructed my docker-compose file to build the container instead of pulling an image. This allowed me to supply args to change the UID and GID. Here is an example of my docker-compose file:

```
version: "3.7"
services:
  ddns-updater:
    build:
      context: https://github.com/qdm12/ddns-updater.git
      args:
        UID: 1026 # Substitute for a user on your NAS
        GID: 100 # Substitute for the user's group on your NAS
    #image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: "bridge"
    ports:
      - 9988:9988/tcp
    volumes:
      - /volume1/docker/ddns-updater/data:/updater/data
    environment:
      - CONFIG=
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s      
           # Web UI
      - LISTENING_PORT=9988
      - ROOT_URL=/
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9995
      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data
      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - SHOUTRRR_ADDRESSES=
    restart: always
```
You'll need to make sure you have Git installed before doing the above. I just installed Git Server using the Synology Package Center; no other config required.
