### DISCUSSION TITLE
Error starting container "invalid character '/'"

### DISCUSSION THREAD

**Discussion by Diejeitor** [qdm12/ddns-updater#541] [Q&A]
Hello, i am runing this container in a Qnap, The problem I have occurs when I start the container and it shows me the following error:

```
2023-10-12T00:33:35+02:00 INFO reading JSON config from environment variable CONFIG
2023-10-12T00:33:35+02:00 ERROR configuration given: cannot unmarshal common settings: invalid character '/' looking for beginning of value
2023-10-12T00:33:35+02:00 INFO Shutdown successful
```

I thought the error was that I had the "/" character in my .json file but I think not

```json
{
    "settings": [
        {
            "provider": "dondominio",
            "domain": "MYDOMAIN",
            "name": "MYCONF",
            "username": "MYUSERNAME",
            "password": "MYPASSWORD",
            "ip_version": "ipv4"
        }
    ]
}
```

This is my YAML code:

```yml
version: "3.7"
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    volumes:
      - ./data:/share/CACHEDEV1_DATA/Container/data
    environment:
      - CONFIG=/share/CACHEDEV1_DATA/Container/data
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s
      - TZ=Europe/Madrid

      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/share/CACHEDEV1_DATA/Container/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - SHOUTRRR_ADDRESSES=
    restart: always
```

But the error persist, can someone help me please?
