### DISCUSSION TITLE
Help? Unable to access the UI with a reverse proxy.

### DISCUSSION THREAD

**Discussion by nedevski** [qdm12/ddns-updater#579] [Q&A]
Hi, I'm unable to access the UI with my reverse proxy.

I have a pretty basic setup - a container with two networks - the default one and one for Nginx Proxy Manager.
There I create a basic binding for `http://ddns-updater:8000/` and give it a URL. This doesn't work.

However when I go to `http://server_up:18000/` everything loads perfectly fine.
All my other services are set up this way and it works fine, but not in this case.

Is there any additional setup that I need to do?
Here is my `docker-compose.yml` file:

```
version: "2.1"

services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    volumes:
      - ./volume:/updater/data
    networks:
      - default
      - nginx
    ports:
      - 18000:8000
    restart: unless-stopped

networks:
  default:
    name: ddns_updater_default
  nginx:
    name: nginx_default
    external: true
```
