### DISCUSSION TITLE
[Help] Unhealthy : Unable to resolve host

### DISCUSSION THREAD

**Discussion by karnalta** [qdm12/ddns-updater#703] [Q&A] [answered]
Hello,

I using DDNS-Updater with Cloudflare and it's working nicely. Great tool !

But, it's always unhealthy.

At first it was failling to the fact that it was resolving mail.mydomain.com as the local IP instead of the real external IP. I had a static DNS entry in my firewall to help resolve the domains inside my LAN. I did't really understand why it was an issue as DDNS is using external website to resolve domain's IP, right ?

So, I removed the static entry from my firewall but now it still fail with the following error :

_ERROR program is unhealthy: lookup  mail.mydomain.com: no such host_

nslookup and/or external tools, resolve it correctly.

Here is my config file :

```json
{
  "settings": [
    {
      "provider": "cloudflare",
      "zone_identifier": "xxxxxxxxxxxxxxxxxxxxxxxxx",
      "domain": "mydomain.com",
      "host": "@, mail",
      "ttl": 600,
      "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "ip_version": "ipv4",
      "ipv6_suffix": ""
    }
  ]
}
```

I certainly do something wrong.. 

Thank for your help.

**Comment by qdm12** [comment]
Are you running it as a binary program or in a docker container?

Is your Cloudflare domain proxied or not?

Have you tried setting the resolver address for example to 1.1.1.1? (see the readme on how to do it with a flag or environment variable).

>  did't really understand why it was an issue as DDNS is using external website to resolve domain's IP, right ?

Your public ip address is found using 3rd party websites such as ipinfo.io. Your domain name is resolved via DNS to get the dns record ip address, in order to check the public ip address and the dns record match or not.

**Reply by karnalta** [reply]
It's running in a docker container.

None of my DNS record are proxied at Cloudflare.

I just tried to specify a resolver but still have the error. Here is my docker-compose file content :
```yml
version: '3.8'

services:

  app:

    image: 'qmcgaw/ddns-updater'

    container_name: 'ddns-updater'

    restart: always

    ports:

      - '8000:8000'

    volumes:

      - ./data:/updater/data

    environment:

      - UPDATE_COOLDOWN_PERIOD=15m

      - RESOLVER_ADDRESS=1.1.1.1:53
```

If I nslookup "mail.mydomain.com"  from  the docker host, it correctly resolve my WAN IP and correspond with ipinfo.io.

I don't understand why DNS resolver work with the main domain but not with a mail subdomain.
