### DISCUSSION TITLE
Getting error on healthcheck

### DISCUSSION THREAD

**Discussion by alejo0121** [qdm12/ddns-updater#769] [Q&A] [answered]
Hello! Recently updated my container to the latest version and I'm getting this error on healthcheck:

`OCI runtime exec failed: exec failed: unable to start container process: exec: "/updater/app": stat /updater/app: no such file or directory: unknown`

The container seems to be working fine but is showing up as unhealthy.

Any ideas on what could be happening?

**Comment by alejo0121** [comment, marked as answer]
I figured this one out myself: I'm using **portainer** and removed the container and then recreated it with the latest tag through the terminal and it's working fine with no healthcheck issues.

**Reply by qdm12** [reply]
Yeah it's portainer which is bugged when it comes to docker image/container update (I've seen it in many cases for different files/docker images). Re-creating fully solves it indeed.

**Comment by smailpouri** [comment]
Im getting a healthcheck error as well when using:

```
{
  "provider": "freedns",
  "domain": "test1.domain.com",
  "token": "H1111116666667777",
  "ip_version": "ipv6",
  "ipv6_suffix": ""
},
```

ipv4 creates no issue. 

I tried deleting the container and the stack completely from scratch in portainer.

**Reply by smailpouri** [reply]
if that helps here is my stack:

```
version: "3.7"
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    networks:
      - ipv6net
    ports:
      - 8100:8100/tcp
    volumes:
      - ${CONF_FOLDER}/data:/updater/data
    environment:
      - CONFIG=
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_ADDRESS=:8100
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - SHOUTRRR_ADDRESSES=
      - TZ=${TZ}
    restart: always
    
networks:
  ipv6net:
    driver: bridge
    enable_ipv6: true
```
