### ISSUE TITLE
IHelp: Invalid API key format

### ISSUE THREAD

**Issue by arthur798** [qdm12/ddns-updater#101]
```
{
    "settings": [
        {
            "provider": "cloudflare",
            "domain": "xxxx.co.uk",
            "host": "@",
	    "zone_identifier": "xxxxx",
	    "ttl": 1,
	    "token": "xxxxx",
	    "ip_version": "ipv4"
        }
     ]
}
```
and my docker-compose looks like this:

```
# DDNS-Updater - Update DDNS on Cloudflare
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    restart: always
    ports:
      - 8000:8000/tcp
    volumes:
      - $USERDIR/docker/ddns-updater/data:/updater/data
    environment:
      - PERIOD=5m
      - IP_METHOD=cycle
      - IPV4_METHOD=cycle
      - IPV6_METHOD=cycle
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data
```

Any ideas why is it complaining about the format? did i miss something?
