### ISSUE TITLE
Help: ERROR cannot write to file "/updater/data/updates.json

### ISSUE THREAD

**Issue by BK-STAR77** [qdm12/ddns-updater#107]
Hello,

After deploy with docker-compose I have this error:

```
Running version latest built on 2020-09-29T22:44:01Z (commit 5b52255)

📣  Support for he.net

🔧  Need help? https://github.com/qdm12/ddns-updater/issues/new
💻  Email? quentin.mcgaw@gmail.com
☕  Slack? Join from the Slack button on Github
💸  Help me? https://github.com/sponsors/qdm12
2020-10-02T15:59:04.966Z	ERROR	cannot write to file "/updater/data/updates.json": open /updater/data/updates.json: permission denied
```

My docker compose:

```yml
  Ddns-updater:
    image: qmcgaw/ddns-updater:latest
    container_name: ddns-updater
    network_mode: bridge
    dns:
      - 1.1.1.1
    ports:
      - 8000:8000/tcp
    volumes:
      - /home/media/ddns-updater/config:/updater/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - CONFIG={"settings":[{"provider":"noip","domain":"xxxx.ddnsking.com","host":"@","username":"xxxxxx@gmail.com","password":"xxxxxx":"ipv4"}]}
      - PERIOD=12h
      - IP_METHOD=cycle
      - IPV4_METHOD=cycle
      - IPV6_METHOD=cycle
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=72h15m # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_ENCODING=console
      - LOG_LEVEL=info
      - NODE_ID=-1 # -1 to disable
      # - GOTIFY_URL=
      # - GOTIFY_TOKEN=
```

thanks in advance
