### ISSUE TITLE
Feature request: Add Linode as a DNS provider 

### ISSUE THREAD

**Issue by AnujRNair** [qdm12/ddns-updater#143]
1. What's the feature?
Please add Linode as a DNS provider

2. Extra information?
- Within the Linode Cloud manager, create a `personalAccessToken` - it will be 64 chars. Assign it the `domain` permissions
- Obtain your `domainId` and `recordId` for the A record you want to update. I did this by inspecting the network tab as I manually updated the record. They will both be integers
- `PUT` request to update the record when your IP changes. Here is the JS to do so:

```
    const newIp = '127.0.0.1';
    const url = `https://api.linode.com/v4/domains/${LINODE_DOMAIN_ID}/records/${LINODE_RECORD_ID}`;
    const response = await fetch(url, {
      headers: {
        Authorization: `Bearer ${LINODE_PERSONAL_ACCESS_TOKEN}`,
        'Content-Type': 'application/json',
      },
      method: 'PUT',
      body: JSON.stringify({
        target: newIp,
      }),
    });
```

On success, a JSON response with the updated A record will be returned to you.

Thanks so much!

**Comment by qdm12** [comment]
Hey there, can you please try with `qmcgaw/ddns-updater:linode`? The documentation is [here](https://github.com/qdm12/ddns-updater/blob/linode/docs/linode.md), together with the readme.md.

I went the long route for some reason. You should just have to specify your `domain`, `host` and `token`. If you A/AAAA record does not exist, it even creates it automagically. It does a bunch of API calls here and there to find your domain ID and record ID from your domain name.

It's not tested though, so it **might not work** the first time 😉

**Comment by AnujRNair** [comment]
Thanks for the quick add!

I deployed the image and it properly detected my current settings, which is great!
I haven't tried deploying the image when no entry exists to see if it properly adds a new entry, and my current IP has yet to expire so I have yet to test the update, but so far so good.

I can force changes in my config if you'd like to test these 2 use cases before merging in?

Thanks again!

**Comment by qdm12** [comment]
> I can force changes in my config if you'd like to test these 2 use cases before merging in?

Yes that would be appreciated! 🎖️  And also thanks for the PR review!

> my current IP has yet to expire so I have yet to test the update, but so far so good.
 
You can set your A record to `127.0.0.1` on the web ui and see if the updater picks up the difference. Give it a few minutes eventually for your web ui changes to propagate.

And you can remove the A record and see if the updater creates it on its update period. But don't worry too much if that's troublesome, we can just 'assume' it works and someone can create an issue if it doesn't. It's also related to #129 which is not supported for all the other DNS for now.

**Comment by AnujRNair** [comment]
I updated my A record in the Linode manager to point to 127.0.01, and an hour later, the record still hasn't been updated back.

Config from docker compose:
```
  ddns-updater:
    container_name: ddns
    image: qmcgaw/ddns-updater:linode
    restart: unless-stopped
    networks:
      - default
    ports:
      - 8082:8082/tcp
    volumes:
      - ${CONFIG}/config/ddns/data:/updater/data
    environment:
      - CONFIG={"settings":[{"provider":"linode","domain":"${LINODE_DOMAIN}","host":"${LINODE_HOST}","token":"${LINODE_TOKEN}","ip_version":"ipv4"}]}
      - PERIOD=15m
      - UPDATE_COOLDOWN_PERIOD=10m
      - IP_METHOD=cycle
      - IPV4_METHOD=cycle
      - IPV6_METHOD=cycle
      - HTTP_TIMEOUT=30s
      
      # Web UI
      - LISTENING_PORT=8082
      - ROOT_URL=/
```

Logs:
```
🔧  Need help? https://github.com/qdm12/ddns-updater/issues/new
💻  Email? quentin.mcgaw@gmail.com
☕  Slack? Join from the Slack button on Github
💸  Help me? https://github.com/sponsors/qdm12
2021-01-17T11:57:08.814-0800	INFO	Found single setting to update record
2021-01-17T11:57:09.356-0800	INFO	Reading history from database: domain ***.com host ***
2021-01-17T11:57:09.357-0800	INFO	healthcheck server: listening on 127.0.0.1:9999
2021-01-17T11:57:09.358-0800	INFO	http server: listening on 0.0.0.0:8082
2021-01-17T11:57:09.359-0800	INFO	backup: disabled
2021-01-17T11:58:56.170-0800	INFO	http server: HTTP GET /
2021-01-17T11:58:56.288-0800	INFO	http server: HTTP GET /favicon.ico
2021-01-17T11:59:04.209-0800	INFO	http server: HTTP GET /
2021-01-17T11:59:04.320-0800	INFO	http server: HTTP GET /favicon.ico
2021-01-17T16:58:52.268-0800	INFO	http server: HTTP GET /
2021-01-17T16:58:52.539-0800	INFO	http server: HTTP GET /favicon.ico
2021-01-17T18:48:27.682-0800	INFO	http server: HTTP GET /
2021-01-17T18:48:27.758-0800	INFO	http server: HTTP GET /favicon.ico
2021-01-17T18:48:41.919-0800	INFO	http server: HTTP GET /
2021-01-17T18:48:41.971-0800	INFO	http server: HTTP GET /favicon.ico
```

Any more info you need from me?
