### ISSUE TITLE
better error handling for shoutrrr

### ISSUE THREAD

**Issue by fredericrous** [qdm12/ddns-updater#233]
1. Is this urgent: No
2. DNS provider(s) you use: Answer here
3. Program version: 51dd14c
4. What are you using to run the container: docker swarm
5. Extra information (optional)

Logs:

```log
========================================
========================================
============= ddns-updater =============
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================
ddns-updater_ddns-updater.1.jkxf5lxc0th8@DADDYSHOME    |
Running version latest built on 2021-08-16T12:40:55Z (commit 51dd14c)
ddns-updater_ddns-updater.1.jkxf5lxc0th8@DADDYSHOME    |
🔧 Need help? https://github.com/qdm12/ddns-updater/discussions/new
🐛 Bug? https://github.com/qdm12/ddns-updater/issues/new
✨ New feature? https://github.com/qdm12/ddns-updater/issues/new
☕ Discussion? https://github.com/qdm12/ddns-updater/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2021/08/19 13:59:50 ERROR error initializing router services: illegal argument in config URL
```

Docker compose file:

```yml
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    user: '${PUID}'
    volumes:
      - ${SHARED_FOLDER}/ddns-updater:/updater/data
    environment:
      - CONFIG=
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - IP_METHOD=cycle
      - IPV4_METHOD=cycle
      - IPV6_METHOD=cycle
      - HTTP_TIMEOUT=10s
      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/
      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data
      # Other
      - LOG_ENCODING=console
      - LOG_LEVEL=debug
      - SHOUTRRR_ADDRESSES=discord://${DISCORD_WEBHOOK}
```

config file:

```
{
    "settings": [
        {
            "provider": "ovh",
            "domain": "daddyshome.fr",
            "host": "@",
            "mode": "api",
            "app_key": "y8tEjbKtbdff9TXO",
            "app_secret": "",
            "consumer_key": ""
        },
        {
            "provider": "ovh",
            "domain": "daddyshome.fr",
            "host": "*",
            "mode": "api",
            "app_key": "",
            "app_secret": "",
            "consumer_key": ""
        }
    ]
}
```

same issue with gandi

Host OS: qnap
