### ISSUE TITLE
Latest image on docker hub causes "exec format error"

### ISSUE THREAD

**Issue by sonnatager** [qdm12/ddns-updater#359]
After pulling the newest image from dockerhub ddns-updater is throwing "exec format error" exceptions when starting container with docker-compose.

#### 2. DNS provider(s) you use:
Strato
#### 3. Program version:

    Running version commit 7fcd0f9

#### 5. Extra information (optional)

docker-compose config:
```yaml
version: "3"
services:
  ddns-updater:
    image: qmcgaw/ddns-updater:latest
    container_name: ddns-updater
    platform: linux/arm64
    ports:
      - 8000:8000/tcp
    volumes:
      - /srv/ddns:/updater/data
    environment:
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=ifconfig,ipinfo
      - PUBLICIPV4_HTTP_PROVIDERS=ipify,noip
      - PUBLICIPV6_HTTP_PROVIDERS=ipify,noip
      - PUBLICIP_DNS_PROVIDERS=cloudflare
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s
      - ROOT_URL=/

      # Web UI
      - LISTENING_PORT=8000

      # Backup
      - BACKUP_PERIOD=24h # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=debug
      - LOG_CALLER=short
      - SHOUTRRR_ADDRESSES=
    restart: always
```
config.json:

```json
{
  "settings": [
    {
      "provider": "strato",
      "domain": "subdomain.domain.tld",
      "host": "@",
      "password": "************",
      "ip_version": "ipv4",
      "provider_ip": true
    }
  ]
}
```

Screenshot of log
![Screenshot from 2022-09-02 14-01-36](https://user-images.githubusercontent.com/37934901/188143611-dca0015d-bd81-4b11-9897-c1fe13a67f79.png)

Host OS:
Raspberry PI 4 Model B
Debian GNU/Linux 11 (bullseye)
OS-Version 11.4
