### ISSUE TITLE
DNS resolver errors with Gluetun `connection refused`

### ISSUE THREAD

**Issue by jimpapi** [qdm12/ddns-updater#445]
i use PIA VPN in my synology (docker)
i succesfully managed to install gluetun to connect to pia and get ip and open port for 61 days
i tried to update my ddns server (afraid.org) by installing ddns-updater in my docker with the ip from gluetun
 (network_mode: "container:gluetun") in my ddns-updater docker .yaml file
but the problems i found:

1)conflicting ports in  healthcheck server (127.0.0.1:9999) of ddns--updater and web port 8000
so i changed the ports in ddns-updater settings :
a) [healthcheck server] listening on 127.0.0.1:9995
b) [http server] listening on :8003

but I get errors on resolving dns:

```
WARN obtaining ipv4 address: try 1 of 3: Get "http://ip1.dynupdate.no-ip.com": dial tcp: lookup ip1.dynupdate.no-ip.com on 127.0.0.1:53: read udp 127.0.0.1:41398->127.0.0.1:53: read: connection refused
```

and goes on refusing all dns connections.

i have tried a lot of things but nothing worked. 
Any ideas please? 
i suppose it's a kind of conflicting servers but every time i changed the 127.0.0.1 to something else didn't work!

Thanks in advance!

1. Is this urgent: Yes
2. Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)

4. What are you using to run the container: docker-compose
5. Extra information (optional)

Logs:

```log

```

Configuration file (**remove your credentials!**):

```yml
version: "3.7"
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: "container:gluetun"
  
    volumes:
      - /volume1/docker/updater/data:/updater/data
    environment:
      - CONFIG=
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s
      
      # Web UI
      - LISTENING_PORT=8003
      - ROOT_URL=/
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9995
      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - SHOUTRRR_ADDRESSES=
    restart: always
```
