### ISSUE TITLE
ERROR	unexpected end of JSON input	{"node_id": 0}

### ISSUE THREAD

**Issue by willholdoway** [qdm12/ddns-updater#49]
I'm getting the error: unexpected end of JSON input	{"node_id": 0}

When trying to use dens-updater for the first time via this entry in the docker compose file:

```yml
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    networks:
      - default
    ports:
      - 8000:8000/tcp
    volumes:
      - $USERDIR/docker/ddns-updater/data:/updater/data
    environment:
      - DELAY=300s
      - ROOT_URL=/
      - LISTENING_PORT=8000
      - LOG_ENCODING=console
      - LOG_LEVEL=info
      - NODE_ID=0
      - HTTP_TIMEOUT=10s
      - GOTIFY_URL=
      - GOTIFY_TOKEN=
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: always
```
