### ISSUE TITLE
Does the healthchecks.io feature recently introduced support self-hosted healthcheck services?

### ISSUE THREAD

**Issue by KillerKelvUK** [qdm12/ddns-updater#701]
Hi, thanks for the great app and sorry to bother you with this but I'm confused as to what functionality is already in place.  If this capability isn't built yet I'll happily raise a feature request following this but thought it worthwhile to check first.

I added "the below" healthcheck directives to my ddns-updater containers compose file and it didn't work where others did. I then revisited this github repo and used google and found a recent [feature request](https://github.com/qdm12/ddns-updater/issues/578) for this functionality.  However reading the description of the environment variables I'm confused as it suggests ddns-updater is waiting for healthchecks.io to reach out to it for checks whereas my expectation is the other way around?  Additionally given there is no way to add in a custom URL for my self-hosted container I don't believe ddns-updater supports this option?

**The Below**
Healthchecks.io provide guides as well as pre-built containers so their application can be self-hosted rather than run on their cloud.  I've recently deployed this container in my home network and now have a number of containers checking into my local healthcheck container.  I've done this via updating my docker-compose.yml and including a custom healthcheck directive as below...

```
some_container:
  container_name: some_container
  restart: unless-stopped
  network_mode: bridge
  ports:
    - 8001:8000/tcp
  volumes:
    - /some_volume:/stuff
  healthcheck:
    test: ["CMD", "curl", "-f", "http://mydomain.local:8015/ping/some_uuid"]
    interval: 1m
    timeout: 5s
    retries: 3
    start_period: 30s
  image: some_image
```
