### ISSUE TITLE
Bug: existing ipv6 address not found from resolution

### ISSUE THREAD

**Issue by capnsmc** [qdm12/ddns-updater#794]
Cloudflare IPv6 update complains about invalid IPv6 address and updates IPv6 at every interval, spamming the log and notifications. The IPv6 address is already set to the correct value, though (by *ddns-updater* itself, no less), and does not need any update.

1. Is this urgent: No
2. DNS provider(s) you use: Cloudflare
3. Program version: "Running version latest built on 2024-08-21T09:38:02.154Z (commit c7dbbcb)", though the issue is not limited to that version. It started ten days ago, the day I got IPv6 connectivity.
4. What are you using to run the container: docker compose
5. Extra information: See below for Docker Compose file and some things I tried.

# Logs:

```log
INFO ipv6 address of any.<domain> is invalid IP and your ipv6 address  is <ipv6 address>
INFO ipv6 address of <domain> is invalid IP and your ipv6 address  is <ipv6 address>
INFO Updating record [domain: <domain> | owner: * | provider: cloudflare | ip: ipv6] to use <ipv6 address>
INFO Updating record [domain: <domain> | owner: @ | provider: cloudflare | ip: ipv6] to use <ipv6 address>
```
These (and the notifications) get repeated every ten minutes

# Configuration file:

```json
{
  "settings": [
    {
      "provider": "cloudflare",
      "zone_identifier": "<zone identifier>",
      "domain": "*.<domain>",
      "ttl": 1,
      "token": "<token>",
      "ip_version": "ipv6"
    },
    {
      "provider": "cloudflare",
      "zone_identifier": "<zone identifier>",
      "domain": "<domain>",
      "ttl": 1,
      "token": "<token>",
      "ip_version": "ipv6"
    },
  ]
}
```
N.b.: This is an excerpt. I have other entries in the configuration file, including the corresponding IPv4 entries for the very same Cloudflare domain. They only differ in the setting for `ip_version` (set to `ipv4`, of course), and they work just fine. I also have entries for other, "historical" domains at other providers that also work just fine (though they are not IPv6, but IPv4-only).

I tried removing everything but the first entry (`*.<domain>`) from the configuration. No change.

I also tried removing `updates.json`. No change.

# Docker Compose file:

```yaml
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    restart: always
    ports:
      - 8250:8000/tcp
    volumes:
      - /srv/container/ddns-updater:/updater/data
    # For IPv6
    network_mode: host
    environment:
      SHOUTRRR_ADDRESSES: gotify://<gotify address>/<gotify token>
      TZ: Europe/Berlin
      LISTENING_ADDRESS: 0.0.0.0:8765
```

Host OS:
Ubuntu 24.04
