### ISSUE TITLE
Help: Web interface not accessible

### ISSUE THREAD

**Issue by ipod86** [qdm12/ddns-updater#812]
I installed the update with the following docker compose using Portainer:

```yml
version: "3.7"
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - 8001:8000/tcp
    volumes:
      - ./data:/updater/data
    environment:
      - CONFIG=
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_ADDRESS=:8001
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - SHOUTRRR_ADDRESSES=
    restart: always
```

However, I cannot access the web interface via port 8001.

![Screenshot_20240913_064925_Chrome](https://github.com/user-attachments/assets/67c4c2e6-f141-4b18-ad30-4e4966d6d983)

```
========================================
========================================
============= ddns-updater =============
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================
Running version latest built on 2024-08-28T14:16:17.081Z (commit bc272e0)
🔧 Need help? https://github.com/qdm12/ddns-updater/discussions/new
🐛 Bug? https://github.com/qdm12/ddns-updater/issues/new
✨ New feature? https://github.com/qdm12/ddns-updater/issues/new
☕ Discussion? https://github.com/qdm12/ddns-updater/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2024-09-13T04:34:26Z INFO Settings summary:
├── HTTP client
|   └── Timeout: 10s
├── Update
|   ├── Period: 5m0s
|   └── Cooldown: 5m0s
├── Public IP fetching
|   ├── HTTP enabled: yes
|   ├── HTTP IP providers
|   |   └── all
|   ├── HTTP IPv4 providers
|   |   └── all
|   ├── HTTP IPv6 providers
|   |   └── all
|   ├── DNS enabled: yes
|   ├── DNS timeout: 3s
|   └── DNS over TLS providers
|       └── all
├── Resolver: use Go default resolver
├── Server
|   ├── Listening address: :8001
|   └── Root URL: /
├── Health
|   └── Server listening address: 127.0.0.1:9999
├── Paths
|   ├── Data directory: /updater/data
|   └── Config file: /updater/data/config.json
├── Backup: disabled
└── Logger
    ├── Level: info
    └── Caller: hidden
2024-09-13T04:34:26Z INFO reading JSON config from file /updater/data/config.json
2024-09-13T04:34:26Z INFO file not found, creating an empty settings file
2024-09-13T04:34:26Z ERROR cannot write configuration to file: open /updater/data/config.json: permission denied
2024-09-13T04:34:26Z INFO Shutdown successful
      
```

EDIT
There seem to be permission problems with the jconfig. json

EDIT 2
After chmod 777 the folder. But But still no access.

```
Running version latest built on 2024-08-28T14:16:17.081Z (commit bc272e0)
🔧 Need help? https://github.com/qdm12/ddns-updater/discussions/new
🐛 Bug? https://github.com/qdm12/ddns-updater/issues/new
✨ New feature? https://github.com/qdm12/ddns-updater/issues/new
☕ Discussion? https://github.com/qdm12/ddns-updater/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2024-09-13T05:09:21Z INFO Settings summary:
├── HTTP client
|   └── Timeout: 10s
├── Update
|   ├── Period: 5m0s
|   └── Cooldown: 5m0s
├── Public IP fetching
|   ├── HTTP enabled: yes
|   ├── HTTP IP providers
|   |   └── all
|   ├── HTTP IPv4 providers
|   |   └── all
|   ├── HTTP IPv6 providers
|   |   └── all
|   ├── DNS enabled: yes
|   ├── DNS timeout: 3s
|   └── DNS over TLS providers
|       └── all
├── Resolver: use Go default resolver
├── Server
|   ├── Listening address: :8001
|   └── Root URL: /
├── Health
|   └── Server listening address: 127.0.0.1:9999
├── Paths
|   ├── Data directory: /updater/data
|   └── Config file: /updater/data/config.json
├── Backup: disabled
└── Logger
    ├── Level: info
    └── Caller: hidden
2024-09-13T05:09:21Z INFO reading JSON config from file /updater/data/config.json
2024-09-13T05:09:21Z INFO Found single setting to update record
2024-09-13T05:09:21Z INFO Reading history from database: domain xxxxxx.xxxowner @ ipv4
2024-09-13T05:09:21Z INFO [healthcheck server] health http server listening on 127.0.0.1:9999
2024-09-13T05:09:21Z INFO [http server] http server listening on [::]:8001
2024-09-13T05:09:21Z INFO [backup] disabled

      
```
