### ISSUE TITLE
Help: FILL THIS TEXT OR ISSUE WILL BE CLOSED

### ISSUE THREAD

**Issue by spupuz** [qdm12/ddns-updater#892]
i have 2 different lines with 2 public IP in load balancing and 2 different domains, i continuosly get unhealty error for the docker container

**TLDR**: *Describe your issue in a one liner here*

1. Is this urgent: Yes
2. DNS provider(s) you use: duckdns, dynu
3. Program version:

    

    `Running version latest built on 2024-12-24T09:20:36.130Z (commit 78f3061)`

4. What are you using to run the container: docker-compose
5. Extra information (optional)

Logs:

```
2024-12-28T21:32:26Z INFO Updating record [domain: xxxxxxxxx.duckdns.org | owner: @ | provider: duckdns | ip: ipv4] to use xxx.xxx.xxx.xxx 

2024-12-28T21:37:28Z INFO ipv4 address of xxxxxxxxx.org is xxx.xxx.xxx.xxx and your ipv4 address is xxx.xxx.xxx.xxx 

2024-12-28T21:37:29Z INFO ipv4 address of xxxxxxxxx.duckdns.org is xxx.xxx.xxx.xxx and your ipv4 address is xxx.xxx.xxx.xxx 

2024-12-28T21:37:29Z INFO Updating record [domain: xxxxxxxxx.org | owner: @ | provider: dynu | ip: ipv4] to use xxx.xxx.xxx.xxx 

2024-12-28T21:37:29Z INFO Updating record [domain: xxxxxxxxx.duckdns.org | owner: @ | provider: duckdns | ip: ipv4] to use xxx.xxx.xxx.xxx 

```

Configuration file (**remove your credentials!**):

```
services: 
  ddns-updater: 
    image: qmcgaw/ddns-updater 
    container_name: ddns-updater 
    network_mode: bridge 
    ports: 
      - 8076:8000/tcp 
    volumes: 
      - /xxxxxxxxxxxxxx/xxxxxxxxxxxxxx/DDNS-Updater/data:/updater/data 
    environment: 
      - CONFIG={"settings":[{"provider":"dynu","domain":"xxxxxx.org","group":"group","username":"xxxxxxxxxx","password":"xxxxxxxx","ip_version":"ipv4","ipv6_suffix":""},{"provider":"duckdns","domain":"xxxxxxxxxxx.duckdns.org","token":"xxxxxxxxxxxxxxxxx","ip_version":"ipv4","ipv6_suffix":""}]} 
      - PERIOD=5m 
      - UPDATE_COOLDOWN_PERIOD=5m 
      - PUBLICIP_FETCHERS=all 
      - PUBLICIP_HTTP_PROVIDERS=all 
      - PUBLICIPV4_HTTP_PROVIDERS=all 
      - PUBLICIPV6_HTTP_PROVIDERS=all 
      - PUBLICIP_DNS_PROVIDERS=all 
      - PUBLICIP_DNS_TIMEOUT=3s 
      - HTTP_TIMEOUT=10s 
      - SHOUTRRR_ADDRESSES=telegram://xxxxxxxxxxxxxxxxxxxxx:xxxxxxxxxxx@telegram/?channels=xxxxxxxxxxx&notification=yes&preview=false&parseMode=html 
      - SHOUTRRR_DEFAULT_TITLE=DDNS Updater       
 
      # Web UI 
      - LISTENING_ADDRESS=:8000 
      - ROOT_URL=/ 
 
 
    restart: always

```

Host OS: debian

**Comment by spupuz** [comment]
Which text i need to fill?

**Comment by carrotice** [comment]
I have the same unhealthy status using dynu.com provider.
_Container health:_
```
Status		unhealthy
Failure count	6098
Last output	ERROR program is unhealthy: lookup IP addresses do not match: xxx.xxx.xxx.32 instead of xxx.xxx.xxx.147 for xxxxxx.dynuddns.com
```
_Docker configuration file:_
```
services:
  ddns-updater:
    image: qmcgaw/ddns-updater:v2.9.0
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    volumes:
      - /xxxx/xxxx/ddnsupdater/data/:/updater/data
    environment:
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=ifconfig,ipinfo,spdyn,ipleak,icanhazip,ident,nnev,wtfismyip
      - PUBLICIPV4_HTTP_PROVIDERS=ipleak,icanhazip,ident,nnev,wtfismyip
      - PUBLICIPV6_HTTP_PROVIDERS=
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s
      - TZ=Europe/Paris
      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
    restart: always
```
_JSON configuration (data/config.json) file for dynu:_
```
{
  "settings": [
	{
     	"provider": "dynu",
	"domain": "xxxxxx.dynuddns.com",
	"username": "xxxx",
     	"password": "xxxx",
     	"ip_version": "ipv4",
      	"ipv6_suffix": ""
	}
  ]
}
```
