### ISSUE TITLE
invalid domain name format "test.services" with docker

### ISSUE THREAD

**Issue by marcuslannister** [qdm12/ddns-updater#92]
It seams that it can not recognize  "test.services" on config file, I change to "test.ser", then is ok.

here is my docker compose file, same as example.
```
version: "3.7"
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    volumes:
      - ./data:/updater/data
    environment:
      - CONFIG=
      - PERIOD=5m
      - IP_METHOD=cycle
      - IPV4_METHOD=cycle
      - IPV6_METHOD=cycle
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_ENCODING=console
      - LOG_LEVEL=info
      - NODE_ID=-1 # -1 to disable
      - GOTIFY_URL=
      - GOTIFY_TOKEN=
    # restart: always
    restart: on-failure
```
